import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { useTranslation } from 'react-i18next'
import {
  Button,
  Card,
  CardContent,
  Notice,
  ProgressBar,
  SidebarTabs,
  TabBar,
  useLayoutGate,
  useRailHost,
  useSidebarHost,
  useSwipeNavigation,
  type TabBarItem,
} from '@whiskeyjack-net/design-system'
import { CircleNotch, DownloadSimple, ImagesSquare } from '@phosphor-icons/react'
import { PLATFORM_LABELS, type Platform } from '@whiskeyjack-net/icon-stack-core'
import { SourceSlots } from '@/components/SourceSlots'
import { PlatformGrid } from '@/components/PlatformGrid'
import { PlatformSettings } from '@/components/PlatformSettings'
import { SizePreview } from '@/components/SizePreview'
import { PLATFORM_ICONS } from '@/lib/platform-icons'
import { useGenerator, PLATFORMS } from '@/contexts/GeneratorContext'

/** The meta tab holding the sources, the platform selection, and the exports. */
const SOURCE_TAB = 'source'

export function Generator() {
  const { t } = useTranslation()
  const { source, platforms, busy, exporting, progress, error, generate } = useGenerator()
  const sidebarHost = useSidebarHost()
  const railHost = useRailHost()
  // The preview moves between the rail and the main column rather than being
  // rendered in both, because it runs the real pipeline -- two copies would
  // regenerate every icon twice per slider tick. Hence a JS read of the gate
  // that CSS uses everywhere else on this page.
  const railDeployed = useLayoutGate('xlwide')

  const enabled = PLATFORMS.filter((p) => platforms[p].enabled)

  const [activeTab, setActiveTab] = useState<string>(SOURCE_TAB)

  // A platform tab disappears when its platform is switched off, which would
  // otherwise leave the page on a tab that no longer exists. Keyed on the
  // joined list rather than the array, which is rebuilt every render.
  const enabledKey = enabled.join(',')
  useEffect(() => {
    if (activeTab !== SOURCE_TAB && !enabledKey.split(',').includes(activeTab)) {
      setActiveTab(SOURCE_TAB)
    }
  }, [enabledKey, activeTab])

  // Computed before the empty-state return so the hooks below run in the same
  // order whether or not a source is loaded.
  const tabItems: TabBarItem[] = [
    {
      id: SOURCE_TAB,
      label: t('generator.sourceTab'),
      icon: <ImagesSquare size={16} />,
      // The one tab that is not a platform; the shimmer marks it as the place
      // the session starts rather than another entry in the list.
      underline: 'shimmer' as const,
    },
    ...enabled.map((p) => {
      const Icon = PLATFORM_ICONS[p]
      return { id: p, label: PLATFORM_LABELS[p], icon: <Icon size={16} /> }
    }),
  ]

  const activeIndex = Math.max(
    0,
    tabItems.findIndex((i) => i.id === activeTab),
  )
  const { swipeOffset, isAnimating, handleTouchStart, handleTouchMove, handleTouchEnd } =
    useSwipeNavigation({
      count: tabItems.length,
      activeIndex,
      onNavigate: (index) => setActiveTab(tabItems[index].id),
    })

  // Before a source exists there is one thing to do, so the page says so and
  // nothing else. Caps at --content-max like every other page, which lines the
  // upload button up with the header's upload pill.
  if (!source) {
    return (
      <div className="mx-auto max-w-[var(--content-max)] px-4 pb-6 pt-3">
        <div className="mb-4 flex flex-col items-center gap-2 py-8">
          {/* The app's own icon, generated by the app. BASE_URL rather than a
              literal, so it survives the base path moving. */}
          <img src={`${import.meta.env.BASE_URL}icon-192.png`} alt="" className="h-16 w-16 rounded-2xl" />
          <h1 className="text-2xl font-bold text-[var(--color-text-primary-light)] dark:text-[var(--color-text-primary-dark)]">
            {t('app.name')}
          </h1>
          <p className="max-w-sm text-center text-sm text-[var(--color-text-muted-light)] dark:text-[var(--color-text-muted-dark)]">
            {t('generator.tagline')}
          </p>
        </div>

        <SourceSlots />
      </div>
    )
  }

  // The preview follows the active tab: every enabled platform stacked on the
  // meta tab (the rail is tall enough to make that a useful overview), just the
  // one platform on a platform tab.
  //
  // Inline, only the single platform ever renders. Each card is a real pipeline
  // run, so an eleven-card overview in the content column would cost eleven
  // renders on the phone that can least afford them -- and it would sit under
  // the source and platform cards, where nobody is looking at it.
  const previewPlatforms = railDeployed && activeTab === SOURCE_TAB ? enabled : [activeTab]
  const previewContent =
    activeTab === SOURCE_TAB && !railDeployed
      ? null
      : previewPlatforms.map((p) => (
          <SizePreview key={p} platform={p as Platform} title={PLATFORM_LABELS[p as Platform]} />
        ))

  const tabs = (
    <>
      {/* The horizontal bar and the vertical rail are the same tabs in two
          presentations; CSS shows exactly one, so tab state stays with the page
          that owns it either way. */}
      <TabBar className="wide:hidden" items={tabItems} activeId={activeTab} onSelect={setActiveTab} />
      {sidebarHost &&
        createPortal(
          <SidebarTabs
            items={tabItems}
            activeId={activeTab}
            onSelect={setActiveTab}
            aria-label={t('generator.platforms')}
          />,
          sidebarHost,
        )}
    </>
  )

  return (
    <>
      {/* Caps and centers at --content-max, then fills the space between the
          panes in the wide..xlwide phase (no rail yet) and re-caps once the rail
          deploys -- so the margins grow with the viewport instead of the text
          measure. */}
      <div
        className="mx-auto max-w-[var(--content-max)] px-4 pb-6 pt-3 wide:max-w-none xlwide:max-w-[var(--content-max)] touch-pan-y"
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        {tabs}

        <div
          className="space-y-4 pt-4 will-change-transform"
          style={{
            transform: swipeOffset !== 0 ? `translateX(${swipeOffset}px)` : undefined,
            transition: isAnimating ? 'transform 0.3s ease-out' : undefined,
            opacity: swipeOffset !== 0 ? Math.max(0.4, 1 - Math.abs(swipeOffset) / 400) : undefined,
          }}
        >
          {activeTab === SOURCE_TAB ? (
            <>
              <SourceSlots />

              <Card>
                <CardContent className="pt-6">
                  <h2 className="mb-3 text-sm font-medium text-[var(--color-text-secondary-light)] dark:text-[var(--color-text-secondary-dark)]">
                    {t('generator.platforms')}
                  </h2>
                  <PlatformGrid />
                </CardContent>
              </Card>

              <Card>
                <CardContent className="pt-6">
                  <h2 className="mb-3 text-sm font-medium text-[var(--color-text-secondary-light)] dark:text-[var(--color-text-secondary-dark)]">
                    {t('generator.export')}
                  </h2>
                  {enabled.length === 0 ? (
                    <p className="text-sm text-[var(--color-text-muted-light)] dark:text-[var(--color-text-muted-dark)]">
                      {t('generator.exportEmpty')}
                    </p>
                  ) : (
                    <>
                      <div className="space-y-2">
                        {enabled.map((p) => {
                          const Icon = PLATFORM_ICONS[p]
                          return (
                            <Button
                              key={p}
                              variant="secondary"
                              className="w-full justify-between"
                              disabled={busy}
                              aria-label={t('generator.downloadPlatform', {
                                platform: PLATFORM_LABELS[p],
                              })}
                              onClick={() => void generate(p)}
                            >
                              <span className="flex items-center gap-2">
                                <Icon size={16} weight="regular" />
                                {PLATFORM_LABELS[p]}
                              </span>
                              {exporting === p ? (
                                <CircleNotch size={16} weight="bold" className="animate-spin" />
                              ) : (
                                <DownloadSimple size={16} weight="bold" />
                              )}
                            </Button>
                          )
                        })}
                      </div>
                      <Button
                        variant="accent"
                        className="mt-3 w-full"
                        disabled={busy}
                        onClick={() => void generate('all')}
                      >
                        {exporting === 'all' ? (
                          <CircleNotch size={16} weight="bold" className="mr-2 animate-spin" />
                        ) : (
                          <DownloadSimple size={16} weight="bold" className="mr-2" />
                        )}
                        {t('generator.exportAll')}
                      </Button>
                    </>
                  )}
                </CardContent>
              </Card>
            </>
          ) : (
            <PlatformSettings platform={activeTab as Platform} />
          )}

          {/* Below xlwide the preview belongs to the content column, under the
              settings it reflects. */}
          {!railDeployed && previewContent}

          {busy && (
            <div role="status" aria-live="polite" className="space-y-2 py-2">
              <ProgressBar value={progress / 100} label={t('generator.generating')} />
              <p className="text-center text-sm text-[var(--color-text-secondary-light)] dark:text-[var(--color-text-secondary-dark)]">
                {t('generator.generatingProgress', { progress })}
              </p>
            </div>
          )}
          {error && <Notice tone="error">{error}</Notice>}
        </div>
      </div>

      {/* At xlwide the preview moves into the rail, where it stays put while the
          settings beside it scroll. AppPanes owns the rail's own padding, so
          the preview's inset from the right edge already mirrors the tab rail's
          from the left. */}
      {railDeployed &&
        railHost &&
        createPortal(<div className="space-y-4">{previewContent}</div>, railHost)}
    </>
  )
}
